### ISSUE TITLE
OpenShift template does not work

### ISSUE THREAD

**Issue by jorgemoralespou** [Produban/monkey-ops#1]
The template does not work OOTB.
It expects a tagged image. If replaced the token with "produban/monkey-ops" before importing the template there's no issue.

It expects a serviceAccount serviceOps.

And then the published container provides a nice core dump
````
panic: interface conversion: interface is nil, not []interface {}

goroutine 5 [running]:
main.GetDCs(0xc820048580, 0x0, 0x0, 0x0)
	/var/lib/jenkins/jobs/monkey-ops/workspace/go/chaos.go:143 +0x66b
main.ExecuteChaos(0xc820048580, 0xc82000a025, 0xa)
	/var/lib/jenkins/jobs/monkey-ops/workspace/go/chaos.go:226 +0x41a
created by main.main
	/var/lib/jenkins/jobs/monkey-ops/workspace/go/monkey-ops.go:72 +0x9fd

goroutine 1 [IO wait]:
net.runtime_pollWait(0x7ff0c86e58d0, 0x72, 0xc82000a1a0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82004b800, 0x72, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82004b800, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).accept(0xc82004b7a0, 0x0, 0x7ff0c86e59c8, 0xc820010f60)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/net/fd_unix.go:408 +0x27c
net.(*TCPListener).AcceptTCP(0xc8200240a0, 0xc8200e7b38, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/net/tcpsock_posix.go:254 +0x4d
net/http.tcpKeepAliveListener.Accept(0xc8200240a0, 0x0, 0x0, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/net/http/server.go:2135 +0x41
net/http.(*Server).Serve(0xc820016420, 0x7ff0c86e5990, 0xc8200240a0, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/net/http/server.go:1887 +0xb3
net/http.(*Server).ListenAndServe(0xc820016420, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/net/http/server.go:1877 +0x136
net/http.ListenAndServe(0x8b6968, 0x5, 0x7ff0c86e48f8, 0xc82000ebe0, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/net/http/server.go:1967 +0x8f
main.main()
	/var/lib/jenkins/jobs/monkey-ops/workspace/go/monkey-ops.go:77 +0xa55

goroutine 8 [IO wait]:
net.runtime_pollWait(0x7ff0c86e5810, 0x72, 0xc82000a1a0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc82004b8e0, 0x72, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc82004b8e0, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc82004b880, 0xc820087400, 0x400, 0x400, 0x0, 0x7ff0c86e0168, 0xc82000a1a0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc8200240b0, 0xc820087400, 0x400, 0x400, 0x0, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8200ea4e0, 0x7ff0c86e5ac8, 0xc8200240b0, 0x5, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc82008c580, 0x97f117, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc82008c580, 0xc8200f9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7ff0c86e5e30, 0xc82008c580, 0xc8200b37b8, 0xc8200f9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc820011a40, 0xc8200f9000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	<autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc820016d80)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820016d80, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8200b3760)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/net/http/transport.go:685 +0xc78

goroutine 9 [select]:
net/http.(*persistConn).writeLoop(0xc8200b3760)
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
	/var/lib/jenkins/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.5/src/net/http/transport.go:686 +0xc9d
````

**Comment by julianfernandez** [comment]
Hello Jorge.

You are right. We have a jenkins job which replace {TAGGED_IMAGE} for the image tag in dockerhub. I´ve fixed this in the template, so now is pointing to dockerhub directly.

About the service account, is documented in the README.md (I have been updated the documentation this morning). The service account must be called monkey-ops.

"Before all is necessary to create a service account (and a token as a secret) with editing permissions within the project that you want to use. The service account must be called monkey-ops.

In this page you can find how to do it: https://docs.openshift.com/enterprise/3.1/dev_guide/service_accounts.html#managing-service-accounts"

**Comment by julianfernandez** [comment]
I´ve also updated the http client error handling in order to show better logs
